random_seed: 42

baseline:
  logistic_regression:
    booster: gblinear
    n_estimators: 120
    learning_rate: 0.1
    reg_alpha: 0.0
    reg_lambda: 1.0
    tree_method: hist
    device: cuda
    n_jobs: 1

  random_forest:
    n_estimators: 1
    num_parallel_tree: 80
    max_depth: 18
    learning_rate: 1.0
    subsample: 0.8
    colsample_bynode: 0.8
    min_child_weight: 2.0
    tree_method: hist
    device: cuda
    n_jobs: 1

  xgboost:
    n_estimators: 200
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    tree_method: hist
    device: cuda
    n_jobs: 1

  hist_gradient_boosting:
    n_estimators: 200
    learning_rate: 0.1
    grow_policy: lossguide
    max_leaves: 31
    max_depth: 0
    min_child_weight: 1.0
    reg_lambda: 1.0
    tree_method: hist
    device: cuda
    n_jobs: 1
